# install: conda env create -f conda_env.yaml
# update: conda env update -f conda_env.yaml --prune

name: behavysis_core
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - ffmpeg
  - pip:
      - behavysis_core
